name: TimerGHG
version: '${version}'
main: com.rechords25.timerghg.TimerGHG
api-version: '1.21'

permissions :
  permission.timer:
    description: "The permission node for the timer."
    default: op

commands:
  timer:
    description: Displays and controls an action bar timer
    usage: /timer <start|pause|reset|color>
    permission: permission.timer
    permission-message: "You do not have permission to use this command"