name: TimerGHG
version: '1.2.0'
main: com.rechords25.timerghg.TimerGHG
api-version: '1.21'

permissions:
  permission.timer:
    description: "The permission node for the timer."
    default: op

commands:
  timer:
    description: Displays and controls an action bar timer
    usage: /timer (start [forward] | pause | stop | reset [time | style | settings | all | defaults] | style (color <color> | bold <value> | italic <value> | underlined <value>) | set <time> | add <time> | subtract <time>)
    permission: permission.timer
    permission-message: "You do not have permission to use this command"